name: ExamplePlugin
version: ${version}
main: dev.alta.example.ExamplePlugin
api-version: '1.20'
depend: [Commons]
authors: [Alta Services]
description: An example plugin showcasing Commons features

